# Site settings
title: Brice's Blog
description: Highlighting some of my more technical adventures
disqus:
  shortname: bricelam
application_insights: bc55e726-6559-4f0c-8c4d-85be3d47ec33
author: Brice Lambson
email: brice@bricelam.net
github_username: bricelam
twitter_username: bricelambs
theme: minima
header_pages:
  - about.md
  - projects.md
paginate: 7
paginate_path: "/page/:num/"
show_excerpts: true

# Build settings
future: true
plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
gfm_quirks: paragraph_end
gist:
  noscript: false
jailed: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
