# Site settings
title: Brice's Blog
description: Highlighting some of my more technical adventures
disqus_shortname: bricelam
google_analytics_tracking_id: UA-57792437-1
author:
  name: Brice Lambson
  email: brice@bricelam.net
  title: Senior Software Engineer
  twitter: bricelambs
  github:  bricelam

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
gist:
  noscript: false
kramdown:
  hard_wrap: false
  input: GFM
