# Site settings
title: "Brice's Blog"
email: your-email@domain.com
description: "Highlighting some of my more technical adventures"
baseurl: ""
url: "http://bricelam.net"
twitter_username: jekyllrb
github_username:  jekyll
disqus_shortname: bricelam

# Build settings
markdown: kramdown
permalink: pretty
