# Site settings
title: Brice's Blog
email: bricelam@outlook.com
description: Highlighting some of my more technical adventures
baseurl: ""
url: "http://www.bricelam.net"
twitter_username: bricelambs
github_username:  bricelam
disqus_shortname: bricelam
jobtitle: Software Engineer II
google_analytics_tracking_id: UA-57792437-1

# Build settings
markdown: kramdown
gems:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
