# Site settings
title: Brice's Blog
description: Highlighting some of my more technical adventures
application_insights: bc55e726-6559-4f0c-8c4d-85be3d47ec33
author: Brice Lambson
email: brice@bricelam.net
github_username: bricelam
twitter_username: bricelambs
youtube_channel: UCKQoPIhSjqnnq20sD9fGbeA
rss: RSS
header_pages:
  - about.md
  - projects.md
  - tags/index.html
  - links.md
paginate: 7
paginate_path: "/page/:num/"
show_excerpts: true
future: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
