# Site settings
title: Brice's Blog
email: bricelam@outlook.com
description: Highlighting some of my more technical adventures
baseurl: ""
url: "http://bricelam.net"
twitter_username: bricelambs
github_username:  bricelam
disqus_shortname: bricelam
jobtitle: Software Development Engineer II

# Build settings
markdown: kramdown
permalink: pretty
gems:
  - jekyll-redirect-from
