# Site settings
name: Brice's Blog
description: Highlighting some of my more technical adventures
baseurl: ""
url: "http://www.bricelam.net"
disqus_shortname: bricelam
google_analytics_tracking_id: UA-57792437-1
author:
  name: Brice Lambson
  email: bricelam@outlook.com
  title: Senior Software Engineer
  twitter: bricelambs
  github:  bricelam

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
gist:
  noscript: false
kramdown:
  hard_wrap: false
  input: GFM
